name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.4-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: golang
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run migrations
      run: docker run -v "D:/ANO_2022/Software Small Bank/api/db/migration:/migrations" --network host migrate/migrate
          -path=/migrations/ -database "postgresql://root:golang@localhost:5432/simple_bank?sslmode=disable" up

    - name: Test
      run: make test
